<a href="https://colab.research.google.com/github/ggrgrtr/rest/blob/main/Labs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = "https://drive.google.com/uc?export=download&id=1MVbh3ReFZEw3uKreAj2s0ftYiUHvT0qa"
df = pd.read_csv(url)# загружаем таблицу в переменную df
df.head()

ts             device        co   humidity  light       lpg  \
0  1.595201e+09  b8:27:eb:bf:9d:51  0.005951  49.400000  False  0.008733   
1  1.594665e+09  00:0f:00:70:91:0a  0.004878  74.599998  False  0.007563   
2  1.595000e+09  1c:bf:ce:15:ec:4d  0.004009  69.699997   True  0.006563   
3  1.594591e+09  b8:27:eb:bf:9d:51  0.005304  51.700000  False  0.008036   
4  1.595176e+09  00:0f:00:70:91:0a  0.002216  76.099998  False  0.004275   

   motion     smoke       temp  
0   False  0.023511  21.500000  
1   False  0.020162  19.100000  
2   False  0.017327  25.900000  
3   False  0.021509  22.100000  
4   False  0.010960  19.299999

In [ ]:
print("Размер датасета:", df.shape)
print(" Заголовки столбцов:")
print(df.columns.tolist())

Размер датасета: (324147, 9)
 Заголовки столбцов:
['ts', 'device', 'co', 'humidity', 'light', 'lpg', 'motion', 'smoke', 'temp']


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324147 entries, 0 to 324146
Data columns (total 9 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   ts        324147 non-null  float64
 1   device    324147 non-null  object 
 2   co        324147 non-null  float64
 3   humidity  324147 non-null  float64
 4   light     324147 non-null  bool   
 5   lpg       324147 non-null  float64
 6   motion    324147 non-null  bool   
 7   smoke     324147 non-null  float64
 8   temp      324147 non-null  float64
dtypes: bool(2), float64(6), object(1)
memory usage: 17.9+ MB


In [ ]:
#random 3 lines
df.sample(3)

ts             device        co   humidity  light       lpg  \
185534  1.594526e+09  00:0f:00:70:91:0a  0.002501  75.400002  False  0.004664   
290030  1.594644e+09  b8:27:eb:bf:9d:51  0.005096  53.000000  False  0.007806   
306786  1.594848e+09  b8:27:eb:bf:9d:51  0.005084  46.900000  False  0.007793   

        motion     smoke  temp  
185534   False  0.012031  19.6  
290030   False  0.020855  21.9  
306786   False  0.020817  23.7

In [ ]:
# столбец СО
df['co']

0         0.005951
1         0.004878
2         0.004009
3         0.005304
4         0.002216
            ...   
324142    0.001827
324143    0.004312
324144    0.004557
324145    0.003745
324146    0.004976
Name: co, Length: 324147, dtype: float64

In [ ]:
# столбе СО с 0 по 5 строки
df.loc[0:5,'co']

0    0.005951
1    0.004878
2    0.004009
3    0.005304
4    0.002216
5    0.005225
Name: co, dtype: float64

In [ ]:
# столбе_2 с 0 по 5 строки
df.iloc[0:5,2]

0    0.005951
1    0.004878
2    0.004009
3    0.005304
4    0.002216
Name: co, dtype: float64

In [ ]:
piece=df[['device','co']]
piece.shape

(324147, 2)

In [ ]:
piece2=df.iloc[:,:3]
piece2.shape
piece2.head()

ts             device        co
0  1.595201e+09  b8:27:eb:bf:9d:51  0.005951
1  1.594665e+09  00:0f:00:70:91:0a  0.004878
2  1.595000e+09  1c:bf:ce:15:ec:4d  0.004009
3  1.594591e+09  b8:27:eb:bf:9d:51  0.005304
4  1.595176e+09  00:0f:00:70:91:0a  0.002216

In [ ]:
df['temp_new']=((df['temp']<18) | (df['temp']>28)).astype(bool)
df.loc[20:30,['temp','temp_new']]

temp  temp_new
20  21.7     False
21  27.0     False
22  21.9     False
23  22.5     False
24  19.1     False
25  22.3     False
26  22.2     False
27  23.2     False
28  28.6      True
29  19.1     False
30  24.0     False

In [ ]:
df['temp_new'].value_counts()

temp_new
False    307621
True      16526
Name: count, dtype: int64

In [ ]:
import numpy as np
df_new = np.random.randint(1, 100, size=324147)
df_new

array([ 6, 17, 28, ..., 31,  4, 23])

In [ ]:
# добавление
df['new_column']=df_new
df.head()

ts             device        co   humidity  light       lpg  \
0  1.595201e+09  b8:27:eb:bf:9d:51  0.005951  49.400000  False  0.008733   
1  1.594665e+09  00:0f:00:70:91:0a  0.004878  74.599998  False  0.007563   
2  1.595000e+09  1c:bf:ce:15:ec:4d  0.004009  69.699997   True  0.006563   
3  1.594591e+09  b8:27:eb:bf:9d:51  0.005304  51.700000  False  0.008036   
4  1.595176e+09  00:0f:00:70:91:0a  0.002216  76.099998  False  0.004275   

   motion     smoke       temp  temp_new  new_column  
0   False  0.023511  21.500000     False           6  
1   False  0.020162  19.100000     False          17  
2   False  0.017327  25.900000     False          28  
3   False  0.021509  22.100000     False          64  
4   False  0.010960  19.299999     False          95

In [ ]:
# переименование
df.rename(columns={'new_column':'Changed'},inplace=True)
df.head()

ts             device        co   humidity  light       lpg  \
0  1.595201e+09  b8:27:eb:bf:9d:51  0.005951  49.400000  False  0.008733   
1  1.594665e+09  00:0f:00:70:91:0a  0.004878  74.599998  False  0.007563   
2  1.595000e+09  1c:bf:ce:15:ec:4d  0.004009  69.699997   True  0.006563   
3  1.594591e+09  b8:27:eb:bf:9d:51  0.005304  51.700000  False  0.008036   
4  1.595176e+09  00:0f:00:70:91:0a  0.002216  76.099998  False  0.004275   

   motion     smoke       temp  temp_new  Changed  
0   False  0.023511  21.500000     False        6  
1   False  0.020162  19.100000     False       17  
2   False  0.017327  25.900000     False       28  
3   False  0.021509  22.100000     False       64  
4   False  0.010960  19.299999     False       95

In [ ]:
# удаление столбца
df=df.drop(columns=['Changed'])
df.head()

ts             device        co   humidity  light       lpg  \
0  1.595201e+09  b8:27:eb:bf:9d:51  0.005951  49.400000  False  0.008733   
1  1.594665e+09  00:0f:00:70:91:0a  0.004878  74.599998  False  0.007563   
2  1.595000e+09  1c:bf:ce:15:ec:4d  0.004009  69.699997   True  0.006563   
3  1.594591e+09  b8:27:eb:bf:9d:51  0.005304  51.700000  False  0.008036   
4  1.595176e+09  00:0f:00:70:91:0a  0.002216  76.099998  False  0.004275   

   motion     smoke       temp  temp_new  
0   False  0.023511  21.500000     False  
1   False  0.020162  19.100000     False  
2   False  0.017327  25.900000     False  
3   False  0.021509  22.100000     False  
4   False  0.010960  19.299999     False

In [ ]:
# Получение строк, удовлетворяющих определенному условию
df[df['temp']>30]

ts             device        co   humidity  light       lpg  \
126     1.595110e+09  1c:bf:ce:15:ec:4d  0.004493  52.500000   True  0.007126   
370     1.595124e+09  1c:bf:ce:15:ec:4d  0.004678  53.799999   True  0.007338   
395     1.595107e+09  1c:bf:ce:15:ec:4d  0.004476  53.299999   True  0.007107   
484     1.595112e+09  1c:bf:ce:15:ec:4d  0.004524  55.299999   True  0.007162   
902     1.595108e+09  1c:bf:ce:15:ec:4d  0.004524  53.700001   True  0.007162   
...              ...                ...       ...        ...    ...       ...   
323304  1.594854e+09  1c:bf:ce:15:ec:4d  0.003777  53.700001   True  0.006286   
323493  1.595109e+09  1c:bf:ce:15:ec:4d  0.004493  53.099998   True  0.007126   
323960  1.594854e+09  1c:bf:ce:15:ec:4d  0.003783  53.700001   True  0.006294   
323979  1.595110e+09  1c:bf:ce:15:ec:4d  0.004499  53.700001   True  0.007133   
324070  1.594855e+09  1c:bf:ce:15:ec:4d  0.003777  53.299999   True  0.006286   

        motion     smoke       temp  temp_new  
126      False  0.018920  30.600000      True  
370      False  0.019521  30.100000      True  
395      False  0.018867  30.200001      True  
484      False  0.019021  30.200001      True  
902      False  0.019021  30.500000      True  
...        ...       ...        ...       ...  
323304   False  0.016547  30.200001      True  
323493   False  0.018920  30.600000      True  
323960   False  0.016568  30.200001      True  
323979   False  0.018940  30.500000      True  
324070   False  0.016547  30.200001      True  

[1885 rows x 10 columns]

In [ ]:
df.to_csv('iot_telemetry_processed.csv', index=False)
print("Сохранено", 'ot_telemetry_processed.csv')

#Excel: можно оставить индекс

df.to_excel('iot_telemetry_processed.xlsx',  index=False)
print("Сохранено", 'ot_telemetry_processed.xlsx')

Сохранено ot_telemetry_processed.csv
Сохранено ot_telemetry_processed.xlsx


In [ ]:
# NUMPY
mass1=np.array([1,2,3],int)
mass2=np.array([4,5,6],int)
mass1[0:2]

array([1, 2])

In [ ]:
print(mass1+mass2)

[5 7 9]


In [ ]:
print(mass1*mass2)

[ 4 10 18]


In [ ]:
print(mass1%mass2)

[1 2 3]


In [ ]:
mass3=np.array([[1,2],[3,4],[5,6]],int)
mass4=np.array([1,2,3],int)
print(mass3*mass3)

[[ 1  4]
 [ 9 16]
 [25 36]]


In [ ]:
zer= np.zeros((2, 4), int)
zer

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
zer_float=np.zeros((2,3))
zer_float

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one=np.ones((2,4),int)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
a = np.array([[1, 2, 3, 4.0],
[5, 6, 7, 8],
[9, 10, 11, 12]])
b=np.copy(a)
b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [ ]:
str(b.sum())

'78.0'

In [ ]:
str(int(b.prod()))

'479001600'

In [ ]:
str(b.mean())

'6.5'

In [ ]:
str(b.min())

'1.0'

In [ ]:
#index of min
str(b.argmin())

'0'

In [ ]:
mass5 = np.array([7, 4, 5, 1], float)
print (sorted(mass5))

[np.float64(1.0), np.float64(4.0), np.float64(5.0), np.float64(7.0)]


In [ ]:
mass6 = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in mass6:
  print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [ ]:
# максимальные значения всех столбцов
df.apply(np.max)

ts          1595203416.979522
device      b8:27:eb:bf:9d:51
co                   0.013505
humidity            99.900002
light                    True
lpg                    0.0158
motion                   True
smoke                0.044288
temp                     30.6
temp_new                 True
dtype: object

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print("Первая строка:", arr[0])
print("Элементs [2, 3] [2,2]:", arr[2, 3],arr[1,3])
print("Последняя строка:", arr[-1])

Первая строка: [1 2 3 4]
Элементs [2, 3] [2,2]: 12 8
Последняя строка: [ 9 10 11 12]


In [ ]:
print(arr,'\n')

print("Простые срезы:")
print("arr[0:2] - первые две строки:")
print(arr[0:2])

print("\narr[:, 1:3] - столбцы 1 и 2:")
print(arr[:, 1:3])

print("\narr[1:, 2:] - с 2 строки, с 3 столбца:")
print(arr[1:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Простые срезы:
arr[0:2] - первые две строки:
[[1 2 3 4]
 [5 6 7 8]]

arr[:, 1:3] - столбцы 1 и 2:
[[ 2  3]
 [ 6  7]
 [10 11]]

arr[1:, 2:] - с 2 строки, с 3 столбца:
[[ 7  8]
 [11 12]]


In [ ]:
print(arr,"\n\nСрезы с шагом:")
print("arr[::2] - каждая вторая строка:")
print(arr[::2])

print("\narr[:, ::2] - каждый второй столбец:")
print(arr[:, ::2])

print("\narr[::-1] - строки в обратном порядке:")
print(arr[::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Срезы с шагом:
arr[::2] - каждая вторая строка:
[[ 1  2  3  4]
 [ 9 10 11 12]]

arr[:, ::2] - каждый второй столбец:
[[ 1  3]
 [ 5  7]
 [ 9 11]]

arr[::-1] - строки в обратном порядке:
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print(arr)
print()
print(arr>10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[False False False False]
 [False False False False]
 [False False  True  True]]


In [ ]:
# новый датасет

!pip install gdown -q
# импортируем pandas
import gdown, pandas as pd

file_id = "1qq6rk9YwRE_AwxUO7_xbRwq0OJPwtYsb"
url = f"https://drive.google.com/uc?id={file_id}"

# Скачиваем файл
gdown.download(url, "robot_dataset.csv", quiet=False)

# Загружаем в Pandas
rd = pd.read_csv("robot_dataset.csv")

Downloading...
From (original): https://drive.google.com/uc?id=1qq6rk9YwRE_AwxUO7_xbRwq0OJPwtYsb
From (redirected): https://drive.google.com/uc?id=1qq6rk9YwRE_AwxUO7_xbRwq0OJPwtYsb&confirm=t&uuid=962f4105-0dc2-4fa7-97f6-2e132346006f
To: /content/robot_dataset.csv
100%|██████████| 174M/174M [00:01<00:00, 104MB/s] 


In [ ]:
rd.head()

test  time  battery_voltage_computer  battery_current_computer  \
0     1   0.0                 25.687559                 -3.265014   
1     1   0.1                 25.686302                 -3.226152   
2     1   0.2                 25.687559                 -3.219675   
3     1   0.3                 25.696354                 -3.109566   
4     1   0.4                 25.620972                 -2.980026   

   battery_voltage_husky  battery_current_husky  position_x  position_y  \
0              23.730831              -5.500566  -79.945528    40.44369   
1              23.717432              -5.399637  -79.945528    40.44369   
2              23.730831              -5.096851  -79.945528    40.44369   
3              23.821280              -5.130495  -79.945528    40.44369   
4              23.797831              -5.265066  -79.945528    40.44369   

   position_z  orientation_x  ...  angular_y  angular_z  \
0  247.112992      -0.009318  ...  -0.001370   0.001419   
1  247.114304      -0.009318  ...  -0.002070   0.001642   
2  247.115688      -0.009319  ...   0.000148  -0.003457   
3  247.118170      -0.009311  ...  -0.001885  -0.002250   
4  247.119541      -0.009312  ...  -0.001743  -0.000586   

   linear_acceleration_x  linear_acceleration_y  linear_acceleration_z  \
0              -0.202699              -0.182956              -9.812503   
1              -0.195739              -0.183969              -9.820614   
2              -0.198949              -0.184708              -9.810820   
3              -0.197439              -0.182529              -9.796706   
4              -0.197280              -0.182930              -9.802644   

   temperature   humidity  route  speed  payload  
0    30.106937  28.325180      A    1.0       12  
1    30.106937  27.977432      A    1.0       12  
2    30.111963  28.134895      A    1.0       12  
3    30.116987  28.123913      A    1.0       12  
4    30.116987  28.096743      A    1.0       12  

[5 rows x 27 columns]

In [ ]:
rd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386369 entries, 0 to 386368
Data columns (total 27 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   test                      386369 non-null  int64  
 1   time                      386369 non-null  float64
 2   battery_voltage_computer  386369 non-null  float64
 3   battery_current_computer  386369 non-null  float64
 4   battery_voltage_husky     386369 non-null  float64
 5   battery_current_husky     386369 non-null  float64
 6   position_x                386369 non-null  float64
 7   position_y                386369 non-null  float64
 8   position_z                386369 non-null  float64
 9   orientation_x             386369 non-null  float64
 10  orientation_y             386369 non-null  float64
 11  orientation_z             386369 non-null  float64
 12  orientation_w             386369 non-null  float64
 13  velocity_x                386369 non-null  f

In [ ]:
rd.iloc[::2]

test    time  battery_voltage_computer  battery_current_computer  \
0          1    0.00                 25.687559                 -3.265014   
2          1    0.20                 25.687559                 -3.219675   
4          1    0.40                 25.620972                 -2.980026   
6          1    0.61                 25.720224                 -3.057750   
8          1    0.80                 25.669970                 -3.316830   
...      ...     ...                       ...                       ...   
386360   113  453.20                 25.087019                 -1.082265   
386362   113  453.40                 25.087019                 -1.036926   
386364   113  453.60                 25.092045                 -1.088742   
386366   113  453.80                 25.105864                 -1.069311   
386368   113  454.00                 25.097071                 -1.069311   

        battery_voltage_husky  battery_current_husky  position_x  position_y  \
0                   23.730831              -5.500566  -79.945528   40.443690   
2                   23.730831              -5.096851  -79.945528   40.443690   
4                   23.797831              -5.265066  -79.945528   40.443690   
6                   23.811230              -5.231423  -79.945528   40.443690   
8                   23.720781              -5.579065  -79.945528   40.443689   
...                       ...                    ...         ...         ...   
386360              24.920053              -4.098781  -79.946131   40.442014   
386362              24.866455              -4.379138  -79.946131   40.442014   
386364              24.896603              -4.199709  -79.946131   40.442014   
386366              24.822905              -4.278210  -79.946131   40.442014   
386368              24.879854              -4.244567  -79.946131   40.442014   

        position_z  orientation_x  ...  angular_y  angular_z  \
0       247.112992      -0.009318  ...  -0.001370   0.001419   
2       247.115688      -0.009319  ...   0.000148  -0.003457   
4       247.119541      -0.009312  ...  -0.001743  -0.000586   
6       247.122945      -0.009313  ...  -0.001720   0.001231   
8       247.128277      -0.009306  ...   0.001395   0.002597   
...            ...            ...  ...        ...        ...   
386360  252.720399       0.013498  ...  -0.000250  -0.000732   
386362  252.754247       0.013489  ...   0.000606   0.001612   
386364  252.784019       0.013490  ...  -0.001613  -0.001175   
386366  252.793372       0.013492  ...  -0.000593   0.001043   
386368  252.827333       0.013491  ...  -0.003068  -0.002877   

        linear_acceleration_x  linear_acceleration_y  linear_acceleration_z  \
0                   -0.202699              -0.182956              -9.812503   
2                   -0.198949              -0.184708              -9.810820   
4                   -0.197280              -0.182930              -9.802644   
6                   -0.194770              -0.183612              -9.824125   
8                   -0.193530              -0.184177              -9.819398   
...                       ...                    ...                    ...   
386360               0.040892              -0.337572              -9.801969   
386362               0.040835              -0.338684              -9.801738   
386364               0.040822              -0.337973              -9.802111   
386366               0.041431              -0.339294              -9.802654   
386368               0.039091              -0.339882              -9.802012   

        temperature   humidity  route  speed  payload  
0         30.106937  28.325180      A    1.0       12  
2         30.111963  28.134895      A    1.0       12  
4         30.116987  28.096743      A    1.0       12  
6         30.106937  28.069805      A    1.0       12  
8         30.106937  28.118710      A    1.0       12  
...             ...        ...    ...    ...      ...  
386360    22.751301  84.

In [ ]:
print(*rd.columns)

test time battery_voltage_computer battery_current_computer battery_voltage_husky battery_current_husky position_x position_y position_z orientation_x orientation_y orientation_z orientation_w velocity_x velocity_y velocity_z angular_x angular_y angular_z linear_acceleration_x linear_acceleration_y linear_acceleration_z temperature humidity route speed payload


In [ ]:
rd['time'].unique()

array([0.0000e+00, 1.0000e-01, 2.0000e-01, ..., 2.3932e+02, 4.2301e+02,
       4.4522e+02])

In [ ]:
df['device'].unique()

array(['b8:27:eb:bf:9d:51', '00:0f:00:70:91:0a', '1c:bf:ce:15:ec:4d'],
      dtype=object)

In [ ]:
rd['temperature'].value_counts()

temperature
21.575661    1624
21.585711    1431
21.666094    1141
21.565613    1118
21.656046    1023
             ... 
27.087233       1
27.152550       1
31.689688       1
32.563980       1
32.553932       1
Name: count, Length: 6791, dtype: int64

In [ ]:
q=np.random.randint(1,101,10)
print(q)
print(q.sum(),q.mean(),q.prod())

[20 66 12 70 11 66 58 87 23 60]
473 47.3 5605523409024000


In [ ]:
arr = np.random.rand(4, 5)
print(arr)

[[0.02631946 0.81808954 0.44338543 0.0024768  0.93459552]
 [0.3486877  0.43341196 0.09424752 0.19335396 0.24332259]
 [0.4191847  0.32485726 0.3528752  0.72721508 0.97106832]
 [0.97981962 0.2388619  0.02087115 0.95394913 0.2859871 ]]


In [ ]:
df.head()

ts             device        co   humidity  light       lpg  \
0  1.595201e+09  b8:27:eb:bf:9d:51  0.005951  49.400000  False  0.008733   
1  1.594665e+09  00:0f:00:70:91:0a  0.004878  74.599998  False  0.007563   
2  1.595000e+09  1c:bf:ce:15:ec:4d  0.004009  69.699997   True  0.006563   
3  1.594591e+09  b8:27:eb:bf:9d:51  0.005304  51.700000  False  0.008036   
4  1.595176e+09  00:0f:00:70:91:0a  0.002216  76.099998  False  0.004275   

   motion     smoke       temp  temp_new  
0   False  0.023511  21.500000     False  
1   False  0.020162  19.100000     False  
2   False  0.017327  25.900000     False  
3   False  0.021509  22.100000     False  
4   False  0.010960  19.299999     False

In [ ]:
df['co']=df['co']*1000
df['co']

0         5950.787471
1         4877.736829
2         4009.305163
3         5303.707593
4         2216.388708
             ...     
324142    1826.984776
324143    4312.293277
324144    4557.302419
324145    3744.628050
324146    4976.012340
Name: co, Length: 324147, dtype: float64

In [ ]:
#df["temp_alert"] = ((df["temp"] < 18) | (df["temp"] > 28)).astype(bool)
import matplotlib.pyplot as plt

print(df.loc[0:3,['light']],'\n')


df_light_true = df[df['light'] == True]

# Выводим информацию о новом DataFrame
print("Исходный DataFrame:")
print(f"Количество строк: {len(df)}")
print(f"Количество строк с light=True: {len(df_light_true)}")
print("\nНовый DataFrame (только light=True):")
print(df_light_true.head())
print(f"\nРазмер нового DataFrame: {df_light_true.shape}")

   light
0  False
1  False
2   True
3  False 

Исходный DataFrame:
Количество строк: 324147
Количество строк с light=True: 89915

Новый DataFrame (только light=True):
              ts             device           co   humidity  light       lpg  \
2   1.595000e+09  1c:bf:ce:15:ec:4d  4009.305163  69.699997   True  0.006563   
6   1.594640e+09  1c:bf:ce:15:ec:4d  4591.309904  59.700001   True  0.007239   
9   1.594533e+09  1c:bf:ce:15:ec:4d  4060.152818  75.900002   True  0.006623   
11  1.594603e+09  1c:bf:ce:15:ec:4d  4742.333500  60.200001   True  0.007411   
12  1.594917e+09  00:0f:00:70:91:0a  2971.650082  72.400002   True  0.005285   

    motion     smoke  temp  temp_new  light2  
2    False  0.017327  25.9     False    True  
6    False  0.019241  23.6     False    True  
9    False  0.017497  25.5     False    True  
11   False  0.019728  26.1     False    True  
12   False  0.013748  19.0     False    True  

Размер нового DataFrame: (89915, 11)
