<a href="https://colab.research.google.com/github/ggrgrtr/rest/blob/main/Start_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as q
import numpy

In [ ]:
q.zeros([3,4])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
q.ones([3,4,2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
list = [[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]]
x=q.Tensor(list)
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x.size()

torch.Size([3, 4])

In [ ]:
x.shape

torch.Size([3, 4])

In [ ]:
x[0], x[1]

(tensor([1., 2., 3., 4.]), tensor([5., 6., 7., 8.]))

In [ ]:
x[0][0],x[0][1]

(tensor(1.), tensor(2.))

In [ ]:
x[:,0], x[:,1]

(tensor([1., 5., 9.]), tensor([ 2.,  6., 10.]))

In [ ]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x+1000

tensor([[1001., 1002., 1003., 1004.],
        [1005., 1006., 1007., 1008.],
        [1009., 1010., 1011., 1012.]])

In [ ]:
y=q.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [ ]:
y+x

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [ ]:
x*y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [ ]:
x/y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [ ]:
y/x

tensor([[12.0000,  5.5000,  3.3333,  2.2500],
        [ 1.6000,  1.1667,  0.8571,  0.6250],
        [ 0.4444,  0.3000,  0.1818,  0.0833]])

In [ ]:
x%y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [ ]:
x.sin()

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [ ]:
x.log()

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [ ]:
x.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [ ]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
mask=(x>=3)
x>3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [ ]:
x[mask]

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
y=x.clone()
y[0][0]=999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [ ]:
x.dtype

torch.float32

In [ ]:
x=x.double()
x.dtype

torch.float64

In [ ]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
x=q.from_numpy(x)
x


tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
x=q.rand([2000,3000])
x

tensor([[0.5505, 0.2150, 0.7674,  ..., 0.2035, 0.0108, 0.8978],
        [0.2877, 0.5709, 0.3991,  ..., 0.9810, 0.2568, 0.5167],
        [0.1760, 0.6334, 0.2851,  ..., 0.8949, 0.2561, 0.3177],
        ...,
        [0.2948, 0.6706, 0.2567,  ..., 0.9361, 0.9632, 0.2764],
        [0.7981, 0.6643, 0.6398,  ..., 0.3547, 0.6150, 0.1072],
        [0.7531, 0.7651, 0.3700,  ..., 0.1777, 0.8360, 0.2976]])

In [ ]:
q.cuda.is_available()

True

In [ ]:
dev =q.device('cuda:0')
x

tensor([[0.5505, 0.2150, 0.7674,  ..., 0.2035, 0.0108, 0.8978],
        [0.2877, 0.5709, 0.3991,  ..., 0.9810, 0.2568, 0.5167],
        [0.1760, 0.6334, 0.2851,  ..., 0.8949, 0.2561, 0.3177],
        ...,
        [0.2948, 0.6706, 0.2567,  ..., 0.9361, 0.9632, 0.2764],
        [0.7981, 0.6643, 0.6398,  ..., 0.3547, 0.6150, 0.1072],
        [0.7531, 0.7651, 0.3700,  ..., 0.1777, 0.8360, 0.2976]])

In [ ]:
x_cuda=x.to(dev)
x_cuda

tensor([[0.5505, 0.2150, 0.7674,  ..., 0.2035, 0.0108, 0.8978],
        [0.2877, 0.5709, 0.3991,  ..., 0.9810, 0.2568, 0.5167],
        [0.1760, 0.6334, 0.2851,  ..., 0.8949, 0.2561, 0.3177],
        ...,
        [0.2948, 0.6706, 0.2567,  ..., 0.9361, 0.9632, 0.2764],
        [0.7981, 0.6643, 0.6398,  ..., 0.3547, 0.6150, 0.1072],
        [0.7531, 0.7651, 0.3700,  ..., 0.1777, 0.8360, 0.2976]],
       device='cuda:0')

In [ ]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 8.81 ms, sys: 61.3 ms, total: 70.1 ms
Wall time: 74.3 ms


*`GPU (видеокарта) справляется эффективнее с подсчетом очень больших тензеров, с маленькими - cpu`*

In [ ]:
%time y_cuda=(x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 1.33 ms, sys: 0 ns, total: 1.33 ms
Wall time: 1.38 ms
